src/Entity/Profile.php
<?php

namespace App\Entity;

use App\Repository\ProfileRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProfileRepository::class)
 */
class Profile
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\OneToOne(targetEntity=User::class, cascade={"persist", "remove"})
     */
    private $email;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_de_naissance;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getEmail(): ?User
    {
        return $this->email;
    }

    public function setEmail(?User $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getDateDeNaissance(): ?\DateTimeInterface
    {
        return $this->date_de_naissance;
    }

    public function setDateDeNaissance(\DateTimeInterface $date_de_naissance): self
    {
        $this->date_de_naissance = $date_de_naissance;

        return $this;
    }
}

src/Form/ProfileType.php
<?php

namespace App\Form;

use App\Entity\Profile;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProfileType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Nom')
            ->add('Prenom')
            ->add('image', FileType::class, array('data_class' => null,'required' => false))
            ->add('date_de_naissance');
         
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Profile::class,
        ]);
    }
}

src/Controller/ProfileController.php
<?php

namespace App\Controller;

use App\Entity\Profile;
use App\Form\ProfileType;
use App\Repository\ProfileRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/profile")
 */
class ProfileController extends AbstractController
{

    /**
     * @Route("/new", name="profile_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {//c sont les parametere qui vont etre ajouté au user aprés linscription
        $profile = new Profile();
        $form = $this->createForm(ProfileType::class, $profile);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if(!$profile->getId()){
                $imageFile =$form->get('image')->getData();
                $fileName=md5(uniqid()).'.'.$imageFile->guessExtension();
                $imageFile->move($this->getParameter('image_directory'),$fileName);
                $profile->setImage($fileName);
                
               
                $profile->setEmail($this->getUser('email'));
                        
                        
            }
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($profile);
            $entityManager->flush();

            return $this->redirectToRoute('profile_show',['id'=> $profile->getId()]);
        }

        return $this->render('profile/new.html.twig', [
            'profile' => $profile,
            'form' => $form->createView(),
        ]);
    }

   /**
     * @Route("/", name="profile_index", methods={"GET"})
     */
    public function index(profileRepository $profileRepository): Response
    {
        return $this->render('profile/index.html.twig', [
            'profiles' => $profileRepository->findAll(),
        ]);
    }

    /**
     * @Route("/{id}", name="profile_show", methods={"GET"})
     */
    public function show(Profile $profile): Response
    {$j=$this->getDoctrine()->getRepository(Profile::class)->findAll();
        $id=$this->$j->get('id');
        return $this->render('profile/show.html.twig', [
            'profile' => $profile,
            
        ]);
    }

    /**
     * @Route("/{id}/edit", name="profile_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Profile $profile): Response
    {
        $form = $this->createForm(ProfileType::class, $profile);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('profile_show');
        }

        return $this->render('profile/edit.html.twig', [
            'profile' => $profile,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="profile_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Profile $profile): Response
    {
        if ($this->isCsrfTokenValid('delete'.$profile->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($profile);
            $entityManager->flush();
        }

        return $this->redirectToRoute('profile_show');
    }
}

templates/profile/_delete_form.html.twig
<form method="post" action="{{ path('profile_delete', {'id': profile.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ profile.id) }}">
    <button class="btn">Delete</button>
</form>

templates/profile/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/profile/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Profile{% endblock %}

{% block body %}
    <h1>Edit Profile</h1>

    {{ include('profile/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('profile_show',{'id': profile.id}) }}">back to list</a>

    {{ include('profile/_delete_form.html.twig') }}
{% endblock %}

templates/profile/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Classe index{% endblock %}

{% block body %}
    <h1>Classe index</h1>

    <h1>Profile</h1>

    <table class="table">
        <tbody>
        {% for profile in profiles %}
         <tr>
                <th>My picture</th>
                <td><img src="{{asset('uploads/')}}{{profile.image}}" style="width:300px; height:300px" alt=""></td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ profile.email}}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ profile.Nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ profile.Prenom }}</td>
            </tr>
           
            <tr>
                <th>Date_de_naissance</th>
                <td>{{ profile.dateDeNaissance ? profile.dateDeNaissance|date('Y-m-d') }}</td>
            </tr>
            <tr><th><a class="genric-btn primary" href="{{ path('profile_edit', {'id': profile.id}) }}">edit</a></th></tr>
            {% endfor %}
        </tbody>
    </table>
    
{% if is_granted('ROLE_USER') %}
    <a  class="btn btn-primary"  href="{{ path('profile_new') }}">Create new</a>
   
{% endif %}   
{% endblock %}

templates/profile/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Profile{% endblock %}

{% block body %}
    <h1>Create new Profile</h1>

    {{ include('profile/_form.html.twig') }}

    <a href="{{ path('home') }}">back to list</a>
{% endblock %}

templates/profile/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profile{% endblock %}

{% block body %}
    <h1>Profile</h1>

    <table class="table">
        <tbody>
         <tr>
                <th>My picture</th>
                <td><img src="{{asset('uploads/')}}{{profile.image}}" style="width:300px; height:300px" alt=""></td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ profile.email}}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ profile.Nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ profile.Prenom }}</td>
            </tr>
           
            <tr>
                <th>Date_de_naissance</th>
                <td>{{ profile.dateDeNaissance ? profile.dateDeNaissance|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('profile_show',{'id': profile.id}) }}">back to list</a>

    <a href="{{ path('profile_edit', {'id': profile.id}) }}">edit</a>

    {{ include('profile/_delete_form.html.twig') }}
{% endblock %}